version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - dir -a
      - REQUIREMENTS=$(find . -type f -iname "requirements.txt")
      - pip3 install -r $REQUIREMENTS --upgrade
      - sam build --build-dir ~/
      - cd ~/
      - pwd
      - dir -a            
artifacts:
  type: zip
  files:
    - packaged-template.yaml