version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - pip3 install --upgrade pip
      - dir -a
      - REQUIREMENTS=$(find . -type f -iname "requirements.txt")
      - pip3 install -r $REQUIREMENTS --upgrade
      - sam build --build-dir ~/
      - cd ~/
      - export SAM_CLI_TELEMETRY=0
      - sam package --output-template-file ~/packaged-template.yaml --s3-bucket tfgm-da-lamdba --s3-prefix "da-snowflake-test"
      - ls -a
      - cd $CODEBUILD_SRC_DIR
artifacts:
  type: zip
  files:
    - ~/packaged-template.yaml