version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - dir -a
      - cd ~/
      - pwd
      - dir -a      
artifacts:
  type: zip
  files:
    - packaged-template.yaml