AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description : An AWS Serverless Application for Lambda HTTP Requests

Resources:

  OutputAreaJsonS3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: tfgm-wallingtonp-test
      #NotificationConfiguration:
      #  LambdaConfigurations:
      #  - Event: 's3:ObjectCreated:Put''
      #    Function: !GetAtt SnowflakeValidate.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
    DeletionPolicy: Delete

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt SnowflakeValidate.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Sub ${AWS::AccountId}
      SourceArn: !GetAtt OutputAreaJsonS3.Arn

  SnowflakeValidate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: snowflake-validate-py
      Role: !GetAtt SnowflakeTestRole.Arn
      CodeUri: lamdba/
      Handler: app.snowflake_validate
      Runtime: python3.7
      MemorySize: 1024
      Timeout: 60
      Events:
        # https://github.com/awslabs/serverless-application-model/issues/124z
        # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3
        BucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref OutputAreaJsonS3
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .json
      Environment:
        Variables:
          env: dev


  ##############################
  ### Policies and Roles ####
  ##############################

  SnowflakeTestRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [!Ref "AWS::Region", "snowflake-test-role"] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
      - PolicyName: SystemsManagerGetParameter
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Action:
            - ssm:GetParameterHistory
            - ssm:GetParametersByPath
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: "*"